services:
  postgres:
    image: postgres:16-alpine
    container_name: my-game-shelf-postgres
    environment:
      POSTGRES_USER: ${DB_USER:-mygameshelf}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-120915le}
      POSTGRES_DB: ${DB_NAME:-my_game_shelf}
    ports:
      - "5432:5432"  # So the Go app can connect
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U mygameshelf -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev: # Uses default driver (local)